---
- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
      - stx-release-notes-jobs
    check:
      jobs:
        - openstack-tox-linters
        - nfv-tox-pep8
        - nfv-tox-py27
        - nfv-tox-py37
        - nfv-tox-pylint
        - nova-api-proxy-tox-pep8
        - nova-api-proxy-tox-pylint
    gate:
      jobs:
        - openstack-tox-linters
        - nfv-tox-pep8
        - nfv-tox-py27
        - nfv-tox-py37
        - nfv-tox-pylint
        - nova-api-proxy-tox-pep8
        - nova-api-proxy-tox-pylint

- job:
    name: nfv-tox-py27
    parent: tox
    description: Run py27 for nfv
    required-projects:
      - starlingx/fault
    vars:
      tox_envlist: py27
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nfv-tox-py37
    parent: tox
    description: Run py37 for nfv
    required-projects:
      - starlingx/fault
    vars:
      tox_envlist: py37
      tox_extra_args: -c nfv/tox.ini
      bindep_profile: test py37
      python_version: 3.7

- job:
    name: nfv-tox-pep8
    parent: tox
    description: Run pep8 for nfv
    required-projects:
      - starlingx/fault
    vars:
      tox_envlist: pep8
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nfv-tox-pylint
    parent: tox
    description: Run pylint for nfv
    required-projects:
      - starlingx/fault
    vars:
      tox_envlist: pylint
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nova-api-proxy-tox-pep8
    parent: tox
    description: Run pep8 for nova-api-proxy
    vars:
      tox_envlist: pep8
      tox_extra_args: -c nova-api-proxy/tox.ini

- job:
    name: nova-api-proxy-tox-pylint
    parent: tox
    description: Run pylint for nova-api-proxy
    vars:
      tox_envlist: pylint
      tox_extra_args: -c nova-api-proxy/tox.ini

- job:
    name: flock-devstack-nfv
    parent: flock-devstack-base-min
    required-projects:
      - openstack/barbican
      - openstack/python-barbicanclient
      - starlingx/config
      - starlingx/fault
      - starlingx/integ
      - starlingx/metal
      - starlingx/update
    vars:
      tox_envlist: functional
      devstack_services:
        # StarlingX services
        cgtsclient: true
        fm-common: true
        fm-api: true
        fm-rest-api: true
        fm-mgr: true
        nfv-common: true
        nfv-vim: true
        nfv-client: true
      devstack_plugins:
        barbican: https://opendev.org/openstack/barbican
        config: https://opendev.org/starlingx/config
        fault: https://opendev.org/starlingx/fault
        integ: https://opendev.org/starlingx/integ
        metal: https://opendev.org/starlingx/metal
        nfv: https://opendev.org/starlingx/nfv
        update: https://opendev.org/starlingx/update
